[package]
name = "download-image"
version = "0.1.0"
edition = "2018"

[dependencies]
tokio = { version = "1.38.0", features = ["full"] }
reqwest = { version = "0.11", features = ["json"] }
error-chain = "0.12"
tempfile = "3.3"
